### ISSUE TITLE
screen_stack in UIManager

### ISSUE THREAD

**Issue by topisani** [bitfieldaudio/OTTO#146]
`UIManager` should have a stack of `ScreenEnum`, which lets you push and pop momentary screens. It will make mainly `sends` and `master` a bit nicer to work with in the `EngineManager`

**Comment by jmidt** [comment]
Should the "normal" non-momentary screens be in this stack, or should the default case be that this stack is empty?

**Comment by topisani** [comment]
My idea is, the current screen is always the top element of the stack. `push(ScreenEnum)` pushes to the stack, `pop(ScreenEnum s)` pops the first element that equals `s` (from the top), and `jump(ScreenEnum s)` pops whatever is at the top and displays `s` instead

**Comment by jmidt** [comment]
So the typical screen change would be the jump. And the rest is only used for momentary, or subscreens?

**Comment by topisani** [comment]
For now, yes

**Comment by jmidt** [comment]
Would you agree that if `Sends` button is held, and buttons are pressed that change the active channel (`Synth, External In` or a sampler channel), the new screen should simply be the sends screen for the new channel?
(Just to be sure of the expected behaviour before coding)

**Comment by topisani** [comment]
Good point, that makes this slightly more difficult. Maybe hold off on it for now, it might be overkill anyway

**Comment by jmidt** [comment]
Outdated, now that all screens are momentary under long presses. 
(Meaning this has actually been done, with a max stack size of 1)
Closed.
