### ISSUE TITLE
External input - Features?

### ISSUE THREAD

**Issue by jmidt** [bitfieldaudio/OTTO#150]
As it stands, the external audio input has a button on the faceplate so it stands to reason there should be a screen for it when you press it. But for now it is a bit unclear what the exact features of that screen should be?

The external input has a sends engine, meaning that pressing "External input" and then "Sends" lets you choose volume, panning, and how much to send to effects. So we don't need that kind of features on the Input screen itself.

- One obvious feature might just be an on/off selection

Depending on whether the input is mono or stereo, there are some other things:
- The signal going into the audio effects has to be mono, so we might need a control for whether to mix the stereo signal down to mono, or perhaps grab a specific channel. We might even send the two stereo channels to two different effects?

**Comment by topisani** [comment]
I guess we can control the incoming gain as well, that seems like an obvious feature...

Other than that, yes, a stereo balance at least, and maybe in the future separate routing for L/R channels

**Comment by jmidt** [comment]
Following up on the discussion, we figured it would be good to control both L and R gain separately. In general just treating the two channels separately.
This would give us:

- 2 encoders controlling gain. Could be just an L gain encoder and one for R gain, but probably better with a Gain and Balance encoder, since equal gain is still the common use case.
- 1 encoder for stereo routing. There are 3 destinations for the external input, FX1, FX2 and Dry.
For the effects, the three different routings could be L, R, or L+R. For the dry, we can send stereo data so the three choices could be {L, R} (the standard one) or {L, L} or {R, R}. The stereo routing encoder then goes through all (or some) of these 3x3x3=27 possibilities. Panning and all that is done by the Sends screen.
- 1 encoder for convenient on/off toggle.

**Comment by topisani** [comment]
We ended up deciding on the following:

- 1 encoder switching between stereo/dual mono/off
- 2 encoders controlling gain (stereo: gain+balance; dual mono: gain+gain)

And then just hardcoding that in stereo mode, the signal sent to the effects are just L+R
