### ISSUE TITLE
ARP UI

### ISSUE THREAD

**Issue by topisani** [bitfieldaudio/OTTO#152]
We need UI for our ARP Engine. It is a fairly regular arpeggiator, with the following features:

 - PlayModes: [up, down, updown, downup, updowninc, downupinc, manual, chord, random]
 - Octave modes: [boring, +1, +2, +1 unison, fifth unison, -1 & +1]
 - Note length: percentage of time to hold notes
 - Subdivision of master clock: [quarter, quartertriplet, eighth, eighthtriplet, sixteenth]

We probably want to visualize the notes in some way, since some combinations of play modes/octave modes are quite complex.

### Inspiration:
![image](https://user-images.githubusercontent.com/3133596/71779923-ed9b7700-2fbb-11ea-810d-9e546b120eeb.png)
Source: Abletons arpeggiator manual

**Comment by jmidt** [comment]
I wrote some code for the previous iteration for an auto-scaling of dots to visualize the sequence. So if we somehow get the note-data to the screen, we could adapt that code.
