### ISSUE TITLE
Master UI

### ISSUE THREAD

**Issue by jmidt** [bitfieldaudio/OTTO#171]
The current tempo has recently been added to the Master/Volume screen.  There will probably be more things added to this screen later, so we don't need a finished concept - just something that looks nice for now.
The screen looks like this now:
![image](https://user-images.githubusercontent.com/32618198/79150393-fc6aa480-7dc8-11ea-8724-14fb32e2470f.png)
Feel free to keep the volume as is or just changed slightly - we mainly just need to do something about the tempo :)

**Comment by topisani** [comment]
Screenshots either here, or on the closing PR would be very nice when implementing something like this!

**Comment by jmidt** [comment]
That's true. I will add it later today.

**Comment by jmidt** [comment]
![Screenshot from 2020-04-28 16-55-01](https://user-images.githubusercontent.com/32618198/80502633-2e573b80-8971-11ea-8030-ef0106daab39.png)
This is the current graphics. Nothing much changed. We still welcome suggestions, but on a low priority since more things will probably be added to the screen
Ping: @topisani
